from .gcn import GCN
from .sgc import SGC
from .gat import GAT
from .cheby import Cheby
from .appnp import APPNP
from .graphsage import GraphSage
from .graphsage_sampled import GraphSageSample
from .linear import Linear
from .parallel import Parallel
from .parallelweight import ParallelWeightV1
from .parallelweight import ParallelWeightV2
from .parametrized_adj import PGE